#ifndef _EEPROM_MANAGEMENT_H
#define _EEPROM_MANAGEMENT_H

#include <stdio.h>
#include "stm32f10x.h"

#define DATA_Verify_value "NBYF"


/*存储配置*/
#define MASTER_BASE 0x0000
#define MASTER_LONG 0x0200
#define BACKUP_BASE (MASTER_BASE+MASTER_LONG)
#define BACKUP_LONG 0x0200

//数据验证 4Byte
#define DATA_CHECKING_BASE 0x0000
#define DATA_CHECKING_LONG 0x04
/*通用存储配置*/
#define CURRENCY_BASE (DATA_CHECKING_BASE+DATA_CHECKING_LONG)
#define CURRENCY_LONG 0x40
//IAP版本 4Byte+4Byte~
#define IAP_VERSION_BASE CURRENCY_BASE
#define IAP_VERSION_LONG 0x04
//APP版本 4Byte+4Byte~
#define APP_VERSION_BASE (IAP_VERSION_BASE+IAP_VERSION_LONG*2)
#define APP_VERSION_LONG 0x04
//软件ID 1Byte+1Byte~
#define SOFTWARE_ID_BASE (APP_VERSION_BASE+APP_VERSION_LONG*2)
#define SOFTWARE_ID_LONG 0x01
//CAN分频值 2Byte+2Byte~
#define CAN_FREQ_DIVISION_BASE (SOFTWARE_ID_BASE+SOFTWARE_ID_LONG*2)
#define CAN_FREQ_DIVISION_LONG 0x02
/*应用存储配置*/
#define APPLICATION_BASE (CURRENCY_BASE+CURRENCY_LONG)
#define APPLICATION_LONG 0x0190
//ADC通道启停 4Byte+4Byte~
#define ADC_SWITCH_BASE APPLICATION_BASE
#define ADC_SWITCH_LONG 0x04
//ADC1采样值1 4Byte+4Byte~
#define ADC1_SAMP1_BASE (ADC_SWITCH_BASE+ADC_SWITCH_LONG*2)
#define ADC1_SAMP1_LONG 0x04
//ADC1采样值2 4Byte+4Byte~
#define ADC1_SAMP2_BASE (ADC1_SAMP1_BASE+ADC1_SAMP1_LONG*2)
#define ADC1_SAMP2_LONG 0x04
//ADC2采样值1 4Byte+4Byte~
#define ADC2_SAMP1_BASE (ADC1_SAMP2_BASE+ADC1_SAMP2_LONG*2)
#define ADC2_SAMP1_LONG 0x04
//ADC2采样值2 4Byte+4Byte~
#define ADC2_SAMP2_BASE (ADC2_SAMP1_BASE+ADC2_SAMP1_LONG*2)
#define ADC2_SAMP2_LONG 0x04
//ADC3采样值1 4Byte+4Byte~
#define ADC3_SAMP1_BASE (ADC2_SAMP2_BASE+ADC2_SAMP2_LONG*2)
#define ADC3_SAMP1_LONG 0x04
//ADC3采样值2 4Byte+4Byte~
#define ADC3_SAMP2_BASE (ADC3_SAMP1_BASE+ADC3_SAMP1_LONG*2)
#define ADC3_SAMP2_LONG 0x04
//ADC4采样值1 4Byte+4Byte~
#define ADC4_SAMP1_BASE (ADC3_SAMP2_BASE+ADC3_SAMP2_LONG*2)
#define ADC4_SAMP1_LONG 0x04
//ADC4采样值2 4Byte+4Byte~
#define ADC4_SAMP2_BASE (ADC4_SAMP1_BASE+ADC4_SAMP1_LONG*2)
#define ADC4_SAMP2_LONG 0x04
//ADC5采样值1 4Byte+4Byte~
#define ADC5_SAMP1_BASE (ADC4_SAMP2_BASE+ADC4_SAMP2_LONG*2)
#define ADC5_SAMP1_LONG 0x04
//ADC5采样值2 4Byte+4Byte~
#define ADC5_SAMP2_BASE (ADC5_SAMP1_BASE+ADC5_SAMP1_LONG*2)
#define ADC5_SAMP2_LONG 0x04
//ADC6采样值1 4Byte+4Byte~
#define ADC6_SAMP1_BASE (ADC5_SAMP2_BASE+ADC5_SAMP2_LONG*2)
#define ADC6_SAMP1_LONG 0x04
//ADC6采样值2 4Byte+4Byte~
#define ADC6_SAMP2_BASE (ADC6_SAMP1_BASE+ADC6_SAMP1_LONG*2)
#define ADC6_SAMP2_LONG 0x04
//ADC7采样值1 4Byte+4Byte~
#define ADC7_SAMP1_BASE (ADC6_SAMP2_BASE+ADC6_SAMP2_LONG*2)
#define ADC7_SAMP1_LONG 0x04
//ADC7采样值2 4Byte+4Byte~
#define ADC7_SAMP2_BASE (ADC7_SAMP1_BASE+ADC7_SAMP1_LONG*2)
#define ADC7_SAMP2_LONG 0x04

ErrorStatus Random_EEPROM_Read(unsigned int address, unsigned char* dates, unsigned int length);
ErrorStatus Random_EEPROM_Write(unsigned int address, unsigned char* dates, unsigned int length);

#endif /*_EEPROM_MANAGEMENT_H */